### PR TITLE
fix(build): remove duplicated and missing import

### PR DESCRIPTION
**Pull request by qkdreyer**

### CODE REVIEW

**Comment by mroi** [comment]
Is this a cosmetic change or does the code fail to compile for you without this change?

In the meantime, I updated to the Mojave branch of GPGMail, so things may have changed entirely.

**Comment by qkdreyer** [comment]
It wasn’t a cosmetic change but a build fix

**Comment by mroi** [comment]
Do you happen to have the error message at hand? And do you know, whether this still occurs with the current GPGMail 3.0 version?

**Comment by qkdreyer** [comment]
Just tried to rebuilt it and all things went smooth. I'm closing this.

**Comment by mroi** [comment]
Thanks for your efforts.

**Pull request closed without merging**
